<?php

namespace App\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;

/**
 * Danhmuc Controller
 *
 * @property \App\Model\Table\DanhmucTable $Danhmuc
 */
class DanhmucController extends AppController
{
    public $paginate = [
        'limit' => 10
    ];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->set('title','Danh mục sản phẩm');
    }

    public function view($id = null)
    {
        $danhmuc = $this->Danhmuc->find()->where(['cat_id' => $id])->toArray();
        $product = TableRegistry::get('Sanpham')->find('all')->where(['cat_id' => $id]);
        $countproduct = ($product->count());
        $this->set('product', $this->paginate($product));
        $this->set('countproduct', ($countproduct));
        $this->set('danhmuc', ($danhmuc));

    }


}
