<?php

namespace App\Controller;

use Cake\Core\Configure;
use Cake\Event\Event;
use Cake\ORM\TableRegistry;

class HomeController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->set('title','Shop thể thao');
    }

    public function index()
    {
        $this->_tblproduct=TableRegistry::get('sanpham');
        $where='sanpham.pro_status=1';
        $order='pro_id desc';
        $order2='pro_count_buy desc';
        $order3='pro_view desc';
        $limit=3;
        $newproduct=$this->_tblproduct->getlistProduct($where,$order,$limit);
        $bestbuyproduct=$this->_tblproduct->getlistProduct($where,$order2,$limit);
        $bestviewproduct=$this->_tblproduct->getlistProduct($where,$order3,$limit);
//        debug($newproduct);
//        die('xxx');
        $this->set('newproduct',$newproduct);
        $this->set('bestbuyproduct',$bestbuyproduct);
        $this->set('bestviewproduct',$bestviewproduct);
    }
}