<?php

namespace App\Controller;

use Cake\Core\Configure;
use Cake\Event\Event;
use Cake\ORM\TableRegistry;

class HomeController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_tblproduct=TableRegistry::get('sanpham');
        $this->_tblcategory=TableRegistry::get('danhmuc');
        $this->set('title','Shop thể thao');
    }

    public function index()
    {
        $where=array();
        $where[]="sanpham.pro_name like '%ao%'";
        $where[]='sanpham.pro_status=1';
        $newproduct=$this->_tblproduct->getlistProduct($where);
        debug($newproduct);
        die('xxx');
    }
}