<?php

namespace App\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;

class SearchController extends AppController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $danhmuc = TableRegistry::get('danhmuc')->find('list')->where(['parent_id != ' => '0'])->toArray();
        $maxprice = TableRegistry::get('sanpham')->find()->select('pro_price')->orderDesc('pro_id')->first();
        $this->set('danhmuc', $danhmuc);
        $this->set('maxprice', $maxprice);
        $this->set('title', 'Tìm kiếm');
    }

    public function index()
    {
        if ($this->request->is(['get'])) {
            if($this->request->getQuery('search')=='Search') {
                $condition = [];
                if ($this->request->getQuery('category') != 0) {
                    $categoory = $this->request->getQuery('category');
                    $condition['cat_id'] = $categoory;
                }
                if ($this->request->getQuery('name') != '') {
                    $name = $this->request->getQuery('name');
                    $condition['pro_name LIKE'] = '%' . $name . '%';
                }
                $sanpham = TableRegistry::get('sanpham')->find('all')->where($condition)->toArray();
                $this->set('sanpham', $sanpham);
            }
        }
    }

}
