<?php

namespace App\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;

class SearchController extends AppController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->set('title', 'Tìm kiếm');
    }

    public function index()
    {
        $danhmuc=TableRegistry::get('danhmuc')->find('list')->where(['parent_id != ' => '0'])->toArray();
        if ($this->request->is('get')) {
            $condition=[];
            if ($this->request->getQuery()!='')
        }
//        echo "<pre>";
//        print_r($options);
//        print_r($danhmuc);
//        die();
        $this->set('danhmuc', $danhmuc);
    }

}
